
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHARLITERAL = 48;
  public static final int GREATERTHANSIGN = 38;
  public static final int INCREMENTBY = 30;
  public static final int CHAR = 7;
  public static final int ASSIGNBY = 36;
  public static final int UMINUS = 51;
  public static final int QUESTIONMARK = 27;
  public static final int UPLUS = 50;
  public static final int INT = 6;
  public static final int SUBTRACTBY = 35;
  public static final int DECREMENTBY = 31;
  public static final int FLOATLITERAL = 47;
  public static final int ANDSIGN = 44;
  public static final int SEMICOLON = 25;
  public static final int DOUBLEEQUALTOSIGN = 39;
  public static final int LBRACKET = 23;
  public static final int ORSIGN = 43;
  public static final int LESSTHANSIGN = 37;
  public static final int BOOL = 9;
  public static final int COMMA = 26;
  public static final int CLASS = 2;
  public static final int GREATERTHANEQUALTOSIGN = 41;
  public static final int ADDBY = 34;
  public static final int MULTIPLYBY = 32;
  public static final int RPARENTHESIS = 20;
  public static final int IF = 14;
  public static final int ID = 45;
  public static final int EOF = 0;
  public static final int LESSTHANEQUALTOSIGN = 40;
  public static final int RETURN = 5;
  public static final int PRINTLINE = 13;
  public static final int TRUE = 17;
  public static final int error = 1;
  public static final int VOID = 3;
  public static final int LPARENTHESIS = 19;
  public static final int INTLITERAL = 46;
  public static final int RCURLYBRACKET = 22;
  public static final int COLON = 28;
  public static final int ELSE = 15;
  public static final int LCURLYBRACKET = 21;
  public static final int READ = 11;
  public static final int FINAL = 4;
  public static final int WHILE = 16;
  public static final int LOZENGESIGN = 42;
  public static final int FLOAT = 10;
  public static final int STRING = 8;
  public static final int STRINGLITERAL = 49;
  public static final int FALSE = 18;
  public static final int DIVIDEBY = 33;
  public static final int RBRACKET  = 24;
  public static final int PRINT = 12;
  public static final int TILDENOTE = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "VOID",
  "FINAL",
  "RETURN",
  "INT",
  "CHAR",
  "STRING",
  "BOOL",
  "FLOAT",
  "READ",
  "PRINT",
  "PRINTLINE",
  "IF",
  "ELSE",
  "WHILE",
  "TRUE",
  "FALSE",
  "LPARENTHESIS",
  "RPARENTHESIS",
  "LCURLYBRACKET",
  "RCURLYBRACKET",
  "LBRACKET",
  "RBRACKET ",
  "SEMICOLON",
  "COMMA",
  "QUESTIONMARK",
  "COLON",
  "TILDENOTE",
  "INCREMENTBY",
  "DECREMENTBY",
  "MULTIPLYBY",
  "DIVIDEBY",
  "ADDBY",
  "SUBTRACTBY",
  "ASSIGNBY",
  "LESSTHANSIGN",
  "GREATERTHANSIGN",
  "DOUBLEEQUALTOSIGN",
  "LESSTHANEQUALTOSIGN",
  "GREATERTHANEQUALTOSIGN",
  "LOZENGESIGN",
  "ORSIGN",
  "ANDSIGN",
  "ID",
  "INTLITERAL",
  "FLOATLITERAL",
  "CHARLITERAL",
  "STRINGLITERAL",
  "UPLUS",
  "UMINUS"
  };
}

